In [1]:
from env import config, BASE_DIR
from sqlalchemy import create_engine, text

In [2]:
DATABASE_URL = config("HOUSING_DATABASE_URL", cast=str, default=None)
DATABASE_URL is not None

True

In [3]:
engine = create_engine(str(DATABASE_URL))

In [4]:
DATASET_DIR = BASE_DIR / "datasets"
DATASET_DIR.exists()

True

In [5]:
HOUSE_CSV = DATASET_DIR / "housing_ds.csv"
HOUSE_CSV.exists()

True

In [8]:
import pandas as pd

In [9]:
df = pd.read_csv(str(HOUSE_CSV))
df.head(n=10)

     saledate      MA   type  bedrooms
0  30/09/2007  441854  house         2
1  31/12/2007  441854  house         2
2  31/03/2008  441854  house         2
3  30/06/2008  441854  house         2
4  30/09/2008  451583  house         2
5  31/12/2008  440256  house         2
6  31/03/2009  442566  house         2
7  30/06/2009  446113  house         2
8  30/09/2009  440123  house         2
9  31/12/2009  442131  house         2

In [10]:
df['date'] = pd.to_datetime(df['saledate'], format="%d/%m/%Y")

In [11]:
df['price'] = df['MA']

In [12]:
df.dtypes

saledate            object
MA                   int64
type                object
bedrooms             int64
date        datetime64[ns]
price                int64
dtype: object

In [13]:
df.head()

     saledate      MA   type  bedrooms       date   price
0  30/09/2007  441854  house         2 2007-09-30  441854
1  31/12/2007  441854  house         2 2007-12-31  441854
2  31/03/2008  441854  house         2 2008-03-31  441854
3  30/06/2008  441854  house         2 2008-06-30  441854
4  30/09/2008  451583  house         2 2008-09-30  451583

In [15]:
out_df = df.copy()[['date', 'price', 'type', 'bedrooms']]

In [16]:
table_name = "kaggle_house_data"
out_df.to_sql(table_name, engine, if_exists='replace', index=False)

347

In [17]:
df.shape

(347, 6)

In [9]:
with engine.connect() as conn:
    results = conn.execute(text(f"SELECT * FROM {table_name} LIMIT 10"))
    print(results.all())

[('30/09/2007', 441854, 'house', 2), ('31/12/2007', 441854, 'house', 2), ('31/03/2008', 441854, 'house', 2), ('30/06/2008', 441854, 'house', 2), ('30/09/2008', 451583, 'house', 2), ('31/12/2008', 440256, 'house', 2), ('31/03/2009', 442566, 'house', 2), ('30/06/2009', 446113, 'house', 2), ('30/09/2009', 440123, 'house', 2), ('31/12/2009', 442131, 'house', 2)]